Repository dsstevens/mixtapev2, pull requests merged in 2024-01, with the labels that each got.

#1 Remove unused Album component from the project
  src/components/Album/Album.css
  src/components/Album/Album.tsx
Labels: bug

#16 Feature/header styling
  package-lock.json
  src/components/AlbumsByYear/AlbumsByYear.css
  src/components/App/App.css
  src/components/Header/Header.css
  src/components/Header/Header.tsx
Labels: enhancement

#24 Update readme
  README.md
Labels: documentation
